### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by coachshea** [sidorares/pugify#16]
I have recently downloaded browserify-jade. It works in terms of compiling the jade into clients side javascript function that I can call but the source maps don't seem to be working. I have enabled source maps on browserify (they are working for my livescript files) and the templates are properly compiling (which indicates that browserify-jade is setup correctly and working), but no source maps. Is there something I need to do to enable source maps that I'm missing? Any help is greatly appreciated.

**Comment by sidorares** [comment]
Hi! Could you put some examples here? Original jade and compiled with sourcemaps

**Comment by coachshea** [comment]
I have included the original jade and the compiled js below, but I feel as 
though I must give some context (sorry for not providing more sooner, I was 
hoping that it was something simple that I was missing). I am using 
browserify-middleware to browserify my files on-the-fly. When I check the 
files in the browser (on both iceweasel and chromium) the livescript files are 
showing up as livescript files without any of the compiled js. The jade files 
are show exactly as you see below, which is, as a javascript file with a 
//@sourcemap at the bottom as opposed to showing the original jade template.

 
#jade
section.views

      article
        address= firstName
        address= lastName

#compiled jade as shown in the browser

var jade = require('jade/lib/runtime.js');
module.exports=function template(locals) {
var jade_debug = [ new jade.DebugItem( 1, "/home/coachshea/projects/live-coach/scripts/views/clientView.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (firstName, lastName) {
var jade_indent = [];


buf.push("\n<section class=\"views\">");


buf.push("\n  <article>");


buf.push("\n    <address>" + (jade.escape(null == (jade_interp = firstName) ? "" : jade_interp)));


buf.push("</address>");


buf.push("\n    <address>" + (jade.escape(null == (jade_interp = lastName) ? "" : jade_interp)));


buf.push("</address>");


buf.push("\n  </article>");


buf.push("\n</section>");

}.call(this,"firstName" in locals_for_with?locals_for_with.firstName:typeof firstName!=="undefined"?firstName:undefined,"lastName" in locals_for_with?locals_for_with.lastName:typeof lastName!=="undefined"?lastName:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "section.views\n\n      article\n        address= firstName\n        address= lastName\n");
}
}
//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiIvaG9tZS9jb2FjaHNoZWEvcHJvamVjdHMvbGl2ZS1jb2FjaC9zY3JpcHRzL3ZpZXdzL2NsaWVudFZpZXcuamFkZS5qcyIsInNvdXJjZXNDb250ZW50IjpbXX0=

**Comment by tellnes** [comment]
Checked the sources in one of my own builds and I'm seeing the same results. I don't think `browserify-middleware` is to blame.

**Comment by coachshea** [comment]
I was hoping that I was just making some little (easily correctable) mistake. 
Any thoughts on what causes this or how to fix it? I have otherwise loved this 
plugin and I was really looking forward to sourcemaps.

Thanks for your help.

**Comment by tellnes** [comment]
@coachshea Start by switching to the browserify cli. Then, try to remove plugins, transforms and files until you see a working bundle. When you see that working bundle, then what you last removed is probably to blame.

If you can provide a small reproducable example, it will be a lot easier to figure out what's the problem.

I do expect that you are using another transform plugin which do not support source maps.

**Comment by coachshea** [comment]
I will try that later today when I am at my home computer. Fyi, the only
other transform that I am using is browserify-livescript (of which I am
the author), which does support source maps and which appears to be
working fine. I'll let you know what I find.

Thanks again for all your help.



On Mon, Dec 14, 2015, at 07:12 AM, Christian Tellnes wrote:
> @coachshea[1] Start by switching to the browserify cli. Then, try to
> remove plugins, transforms and files until you see a working bundle.
> When you see that working bundle, then what you last removed is
> probably to blame.


> If you can provide a small reproducable example, it will be a lot
> easier to figure out what's the problem.


> I do expect that you are using another transform plugin which do not
> support source maps.


>


> — Reply to this email directly or view it on GitHub[2].
>


>



Links:

  1. https://github.com/coachshea
  2. https://github.com/sidorares/browserify-jade/issues/16#issuecomment-164421975

**Comment by coachshea** [comment]
I have tried different combinations including running a single jade file through browserify cli with only browserify-jade enabled. The outputted file is identical to what I posted above.

**Comment by coachshea** [comment]
Sorry, I forgot to post the example. This is the simple example that I've been trying to test with.

# jade
section.views

  article
    address= firstName
    address= lastName

**Comment by tellnes** [comment]
@coachshea Can you confirm if `pugify@1.0.3` fixes your problem?

**Comment by coachshea** [comment]
It appears to be the exact same result.

**Comment by tellnes** [comment]
I'm not having this problem anymore after upgrading all dependencies.

**Comment by coachshea** [comment]
I've tried several times and I still have the same issue. As far as I can 
tell, all of my the dependencies are met. I can't meet the optional dependency 
of fsevents@1.0.8, because I'm on linux, but I do not believe that should be 
the problem.

**Comment by deedw** [comment]
I have the same issue here. pugify 1.0.3 (and browserify-jade 1.0.2) compiles the client javascript but source maps don't show the original jade file, just the compiled javascript version. I've created a gist for a basic test project. https://gist.github.com/deedw/f5982c9c7348255256833af709d42313

Generate the bundle using the browserify command in cli.txt and then open index.html and view sources.

I'm using node v4.4.4, browserify 13.0.0, Safari 9.1 or Chrome 50.

**Comment by deedw** [comment]
I've found the cause of source maps not generating. The javascript code that jade generates with compileDebug: true has changed from that which browserify-jade / pugify is expecting in one of its regexes.

Current jade version (1.11.0) generates lines like the following:

`jade_debug.unshift(new jade.DebugItem( 0, "/folders../test-pugify/test.jade" ));`

which are parsed by a regex in the `withSourceMap` function (line 86). The format must have changed in newer jade version and this regex no longer matches. If you adjust the regex to the following it now works:

`var m = l.match(/^jade(_|\.)debug\.unshift\(new jade\.DebugItem\( ([0-9]+)/);`

Note that this works for jade 1.11.0. Adjustments will be needed when `jade` changes to `pug` and you'll also need to match the text that older versions of jade generate.

**Comment by sidorares** [comment]
@deedw Thanks! would you be able to make PR with your change?

**Comment by deedw** [comment]
PR #21

**Comment by sidorares** [comment]
Thanks!
