### ISSUE TITLE
Error with try catch

### ISSUE THREAD

**Issue by maratfakhreev** [sidorares/pugify#24]
With version 1.0.4 my application has started to throw next errors:
<img width="1273" alt="screen shot 2016-05-29 at 14 51 21" src="https://cloud.githubusercontent.com/assets/1300497/15633130/1a99d0d4-25b7-11e6-8769-91da5a72ea9b.png">

I have found problem in these lines of code:
https://github.com/sidorares/pugify/commit/179c4b5259efb9d57c3045bfc932ea70ee7acad3#diff-168726dbe96b3ce427e7fedce31bb0bcR114

Any ideas? I just do not fully understand the meaning of this code block.

**Comment by sidorares** [comment]
would it be easy to create a minimal fully self contained example?

**Comment by maratfakhreev** [comment]
Each `.pug` file throws this error, it doesn't look like some syntax error. You can find all templates [here](https://github.com/fs/backbone-base/tree/master/app/src/templates).
And as I said below if comment lines [115-120](https://github.com/sidorares/pugify/commit/179c4b5259efb9d57c3045bfc932ea70ee7acad3#diff-168726dbe96b3ce427e7fedce31bb0bcR114) it works correctly as works version 1.0.3.

**Comment by sidorares** [comment]
@deedw could you have a look? It seems that sometimes `try {` line is there but `catch` is removed

**Comment by deedw** [comment]
@maratfakhreev Which version of jade/pug are you using?

**Comment by maratfakhreev** [comment]
@deedw Actually I don't define versions of jade/pug in my package.json but they installed as dependencies for another libs. So pug has latest versions but jade has 0.24.x and the problem seems to be in this. After I installed latest version manually everything worked correctly. So, thank you for the idea)

But to avoid this issue and in case of npm 3 jade must be placed in `dependences` not in `peerDependencies`, especially b/c it has required inside the index file. I can prepare PR with this change if you agree with my solution.

**Comment by maratfakhreev** [comment]
Refer to #26
