### ISSUE TITLE
When using pugify got Cannot find module 'jade/lib/runtime.js'

### ISSUE THREAD

**Issue by AndrewBryukhov** [sidorares/pugify#32]
When using pugify got: "Cannot find module 'jade/lib/runtime.js'"

app.js:
`browserify.settings({ transform: ['pugify']});`

How to fix this?

**Comment by deedw** [comment]
The latest version of pugify isn't yet published to npm (@sidorares can you publish?), but removes dependency on jade 1.x.

You'll just need to ensure that you include "pug-runtime" in your client dependencies for browserify to package.

Pending the updated version being available on npm, you can use module direct from github:

```
npm install -D sidorares/pugify

```

**Comment by sidorares** [comment]
@deedw @AndrewBryukhov - done, v2.1.0
